### PR TITLE
Todo List Project

### PR DESCRIPTION
**Pull request by Emmyn5600**
## This pull request contains the following features:

* ### Updated the Readme file
* ### Created the button to add project
* ### Created the button to add the list or tasks

### CODE REVIEW

**Review by umararshadbut — CHANGES_REQUESTED** [review]
# Status: REQUIRED CHANGES :warning: :construction: 

Hi @Emmyn5600 and @Addis0943 
Such a remarkable project you made :+1: ! Awesome README :100: !
We, however, do have a few changes to carry out before we proceed.

##

Kindly work on the suggested changes  👇.
#### Application

- [ ] It is separated in modules ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/javascript/todo_list/modules_requirement.png) from [Odin](https://www.theodinproject.com/courses/javascript/lessons/todo-list))
- [ ] DOM-Manipulation and Logic are in separate modules ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/javascript/todo_list/modules_requirement.png) from [Odin](https://www.theodinproject.com/courses/javascript/lessons/todo-list))
- [ ] It uses localStorage to save todos between sessions ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/javascript/todo_list/localstorage_requirement.png) from [Odin](https://www.theodinproject.com/courses/javascript/lessons/todo-list))

#### Interface 


- [ ] User can edit the details of a to-do item.([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/javascript/todo_list/ui_requirement.png) from [Odin](https://www.theodinproject.com/courses/javascript/lessons/todo-list))

#### Projects ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/javascript/todo_list/projects_requirement.png) from [Odin](https://www.theodinproject.com/courses/javascript/lessons/todo-list))

- [x] The application allows to have different projects (or separate lists of to-dos)
- [x] The user can assign a to-do list items to a project


#### Project specific


- [x] Please run common commands like `build`, `development` should be in `package.json` inside `scripts'. Here is a basic example ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/javascript/todo_list/scripts_requirement.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59622602/))

```javascript
"scripts": {
    "dev": "webpack --mode development",
    "build": "webpack --mode production",
    "start": "webpack-dev-server --mode development --open" // optional
  },
```
- [x] Please remove the `console.log` from your `.js` files. ([Screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/javascript/section/console_log_requirement.png))
- [x] Please resolve the conflicts text in `.gitignore` file.


##
- **When you have made the specified changes, please submit another code review. Thank you!**
##
**If you are stuck at any point or have any questions, let me know by leaving a comment here and mentioning me. I will be happy to help**
HAPPY CODING :computer:
**Umair**

**Comment by Addis-Belete** [comment]
Hello,  TSE
Thank you for your feedback. We have tried to work on them, feel free to check on them.

**Review by mahmoud717 — CHANGES_REQUESTED** [review]
### Changes required ♻️ 

**Hello @Emmyn5600 & @Addis0943**

Great job with the project so far it looks amazing, but there are still some changes to be made:
 
---
### Requested 🔴 
Please make sure to finish all of the  requested changes before asking for a review

## Application:
 

- [x] It is separated in modules (screenshot from Odin)
- [x] DOM-Manipulation and Logic are in separate modules (screenshot from Odin)
- [x] It uses localStorage to save todos between sessions (screenshot from Odin)

## Interface:
 
- [x] User can edit the details of a to-do item.(screenshot from Odin)


---

please make these changes and request another code review.

if you have any questions don't hesitate to contact me on slack **MahmoudMohammad**

**Review by mikenath223 — APPROVED** [review]
### CONGRATULATIONS  👏👏👏

This project meets the requirements for approval.

**STATUS: APPROVED ✅**


Don't forget to fill the project completion form👍
Good luck with the next project.

**HAPPY CODING 🎉💻🎉**

**Michgolden Ukeje (CR)**

**Pull request merged**
